runtime: python37

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /manifest\.json
  static_files: manifest.json
  upload: manifest\.json
  expiration: 0m
- url: /service-worker\.js
  static_files: service-worker.js
  upload: service-worker\.js
  expiration: 0m
- url: /.*
  script: auto
  secure: always